### ISSUE TITLE
Research: Database

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/agc_app#2]
Learn about database backends for Flutter apps.  

The default appears to be Firebase. What are the pros and cons of sticking with this one?

**Comment by philipmjohnson** [comment]
Here's a good article on databases: https://blog.codemagic.io/choosing-the-right-database-for-your-flutter-app/

There seem to be two major contenders:

## Hive

Hive is basically a local key-value store.  This means fast performance, very easy to set up and use, and does not require the Internet. There are no costs to AGC associated with it. However, local storage has the following issues:

  * A user cannot access their data across multiple devices (i.e. their phone and their laptop).
  * If the user loses their device, then they've lost their data.

## Firebase

Firebase is more complicated to set up and use, but has the following capabilities:

  * A user can access their across multiple devices.
  * Data is backed up in the cloud so loss of the device is not an issue.
  * There is an "offline" capability which enables work with loss of connectivity.

A significant issue with Firebase is that if AGC is successful, we might outgrow the [Free Tier](https://firebase.google.com/pricing).  This is probably "a good problem to have".

**Comment by mercedezcastro** [comment]
### Firebase

Pros

- [ ] Easily scalable
- [ ] User friendly
- [ ] Cloud-based
- [ ] Authentication and Machine Learning capabilities
- [ ] Integration with Google (Google Analytics, app messaging, etc.)

Cons

- [ ] Tailored for Android Devices (limited Test Lab options for iOS development)
- [ ] Database limitations (querying capabilities)
- [ ] Terrible to migrate if changing in the future


Another option that I saw pop up a lot: **AWS Amplify**. 
It seems like it had ‘cooler’ features (CI/CD workflow, AR/VR, GraphQL, etc.), but would have a steeper learning curve.

I looked into Hive and I’m also heavily leaning towards Firebase. It’s a mature platform that seems easy/quick to get started and perfect for a smaller project.

**Comment by philipmjohnson** [comment]
Let's go with Firebase. It's well documented and sufficient for us at this point in time.
